from tkinter import *
root=Tk()
root.geometry("400x300")
root.title("main")
def topwin():
    top=Toplevel()
    top.geometry("180x100")
    top.title("Toplevel")
    label=Label(top,text="this is a toplevel window ")
    label.pack()
    top.mainloop()
label2=Label(root,text="this is a main window ")
btn=Button(root,text="click here to open another window",command=topwin)
label2.pack()
btn.pack()
root.mainloop()
